name: Build for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install dependencies
      run:  git clone https://github.com/lammertb/libcrc /linux/ext_libraries

    - name: Test build
      run:  make build -C linux